swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /v1/kv:
    get:
      summary: find key values only by labels
      operationId: find key values only by labels
      parameters:
      - name: X-Domain-Name
        in: header
        type: string
      - name: X-Find
        in: header
        description: greedy or exact
        type: string
      responses:
        "200":
          description: get key value success
          schema:
            type: array
            items:
              $ref: '#/definitions/KVBody'
  /v1/kv/{key}:
    get:
      summary: get key values by key and labels
      operationId: get key values by key and labels
      parameters:
      - name: key
        in: path
        required: true
        type: string
      - name: X-Domain-Name
        in: header
        type: string
      - name: X-Find
        in: header
        description: greedy or exact
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/*KVBody'
      responses:
        "200":
          description: get key value success
          schema:
            type: array
            items:
              $ref: '#/definitions/KVBody'
    put:
      summary: create or update key value
      operationId: create or update key value
      parameters:
      - name: key
        in: path
        required: true
        type: string
      - name: X-Domain-Name
        in: header
        description: set kv to other tenant
        type: string
      - name: X-Realm
        in: header
        description: set kv to heterogeneous config server
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/*KVBody'
      responses:
        "200":
          description: "true"
definitions:
  KVBody:
    type: object
    properties:
      Labels:
        type: object
        additionalProperties:
          type: string
      Value:
        type: string
      ValueType:
        type: string
